apiVersion: apps/v1
kind: Deployment
metadata:
    name: orders-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: orderservice
    template:
        metadata:
            labels:
                app: orderservice
        spec:
            containers:
                - name: orderservice
                  image: grzegorzmajmurek/orderservice:latest